### ISSUE TITLE
M6 et M6 International

### ISSUE THREAD

**Issue by mikhoul** [Sphinxroot/Tele-Franco-Direct-#2]
Do you have a link for those channels especially M6 International since https://shls-m6-int-prod-dub.shahid.net/out/v1/a315ab77ee7343a7a17dbe7e32eee3ba/index_2.m3u8 is dead now ?

Regards :octocat:

**Comment by Sphinxroot** [comment]
salut mik    je vois pas ou car je ne lai pas ajouter ici   mais ca fonctionne sur tnt direct  ou sur call of liberty
